### ISSUE TITLE
Use recycer view

### ISSUE THREAD

**Issue by jimxj** [SwagSwap/SwagSwapAndroid#16]

**Comment by vampserv** [comment]
I finished this one, removing staggeredgridview also fixed all the crashes caused by scrolling. can scroll up now too.

**Comment by jimxj** [comment]
cool. 
But pull to refresh still have the same issue.

**Comment by jimxj** [comment]
I will fix the pull to refresh

**Comment by jimxj** [comment]
I fixed the pull to refresh issue
